/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
#/RMG/Processes/OpticalPhysics true
/RMG/Output/ActivateOutputScheme CustomIsotopeFilter
/run/initialize

/RMG/Output/IsotopeFilter/AddIsotope 77 32
/RMG/Output/NtuplePerDetector false

/RMG/Generator/Confine UnConfined

/RMG/Generator/Select MUSUNCosmicMuons
/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/combined_file.dat

/random/setDirectoryName random/
/random/setSavingFlag 1
/run/beamOn 10000000
