/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
/RMG/Processes/OpticalPhysics true #für NeutronenCaptures generieren
/RMG/Output/ActivateOutputScheme LowFidelityOutputScheme

#/RMG/Output/ActivateOutputScheme MyGe77EventFilterOutputScheme
#/RMG/Output/ActivateOutputScheme IsotopeFilter

/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 GrabmayrGammaCascades/156Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 GrabmayrGammaCascades/158Gd-5keV-cascades.txt
/run/initialize

#/process/optical/boundary/verbose 2

#/RMG/Output/IsotopeFilter/AddIsotope 77 32 # Ge77 filter
#/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false

/RMG/Generator/Confine UnConfined

#/RMG/Generator/Select MUSUNCosmicMuons
#/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/combined_file.dat

/RMG/Generator/Select UserDefined
/Cosmogenics/Generator/SetGammasFile gammas/Gammas.csv


#/RMG/Generator/Select GPS
#/gps/particle mu-
#/gps/direction -0.077055 -0.874746 -0.478416
#/gps/position 38.0   800.0   225.8 cm
#/gps/energy 549.4 GeV

#/RMG/Generator/Select CosmicMuons
#/RMG/Generator/CosmicMuons/SkyShape Plane
#/RMG/Generator/CosmicMuons/SkyPlaneHeight 10

/run/beamOn 5

