/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
/RMG/Processes/OpticalPhysics true
#/RMG/Output/ActivateOutputScheme IsotopeFilter
/RMG/Output/ActivateOutputScheme DebugVertexOutputScheme

/RMG/Processes/UseGrabmayrsGammaCascades true

/control/execute ./gdml/macroZylSSD.mac  # Initialisiert Detektoren aus Macro File erstellt mit legend-pygeom-l1000

/run/initialize

/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 ./GrabmayrGammaCascades/156Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 ./GrabmayrGammaCascades/158Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 1 1 ./GrabmayrGammaCascades/2H-5keV-cascades.txt

/process/inactivate Scintillation      # Es sind nicht alle Szintillations Yields in Remage für L1000 definiert. Dadurch kann es zum Abbruch kommen.
#/process/optical/boundary/verbose 2

#/RMG/Output/IsotopeFilter/AddIsotope 77 32 # Ge77 filter
#/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false


#/RMG/Generator/Confine UnConfined
#/RMG/Generator/Select MUSUNCosmicMuons
#/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/combined_file.dat

/RMG/Generator/Select UserDefined
/My/Generator/SingleNCGamma/SetMergedDir /home/tbueger/code/data/optPhotonSensitiveSurface/ncGunPostprocessed/




# 120min
#/run/beamOn 1000000

#1273 NCs mit 1803 Gammas
/run/beamOn 1000