/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
/RMG/Processes/OpticalPhysics true
/RMG/Output/ActivateOutputScheme MyNeutronCaptureOutputScheme
#/RMG/Output/ActivateOutputScheme IsotopeFilter

/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 GrabmayrGammaCascades/156Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 GrabmayrGammaCascades/158Gd-5keV-cascades.txt
/control/execute gdml/macroZylSSD.mac  # Initialisiert Detektoren aus Macro File erstellt mit legend-pygeom-l1000
/run/initialize

/process/inactivate Scintillation      # Es sind nicht alle Szintillations Yields in Remage für L1000 definiert. Dadurch kann es zum Abbruch kommen.
#/process/optical/boundary/verbose 2

#/RMG/Output/IsotopeFilter/AddIsotope 77 32 # Ge77 filter
#/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false

#/RMG/Generator/Confine Volume   ### Wähle alle relevanten Volumen von tank_water
#/RMG/Generator/Confinement/Physical/AddVolume water
#/RMG/Generator/Confinement/Physical/AddVolume skirt
#/RMG/Generator/Confinement/Physical/AddVolume foot
#/RMG/Generator/Confinement/Physical/AddVolume outercryostat
#/RMG/Generator/Select GPS
#/RMG/Generator/Confinement/MaxSamplingTrials 10000
#/gps/particle neutron
#/gps/energy 0.1 eV

/gps/particle opticalphoton
/gps/position 4000 0 0 mm
/gps/energy 3.095 eV
/gps/direction 1 0 0


#/RMG/Generator/Confine UnConfined
#/RMG/Generator/Select MUSUNCosmicMuons
#/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/combined_file.dat

#/RMG/Generator/Select CustomMUSUN
#/Cosmogenics/Generator/SetMUSUNFile musun/combined_file.dat

#/RMG/Generator/Select GPS
#/gps/particle mu-
#/gps/direction -0.077055 -0.874746 -0.478416
#/gps/position 38.0   800.0   225.8 cm
#/gps/energy 549.4 GeV

#/RMG/Generator/Select CosmicMuons
#/RMG/Generator/CosmicMuons/SkyShape Plane
#/RMG/Generator/CosmicMuons/SkyPlaneHeight 10

/run/beamOn 100

