/RMG/Manager/Logging/LogLevel summary

#/tracking/verbose 2

/RMG/Processes/HadronicPhysics Shielding
/RMG/Processes/Realm CosmicRays
/RMG/Processes/OpticalPhysics true
/RMG/Output/ActivateOutputScheme MyNeutronCaptureOutputScheme
#/RMG/Output/ActivateOutputScheme IsotopeFilter

/RMG/Processes/UseGrabmayrsGammaCascades true

/control/execute ./gdml/macroZylSSD.mac  # Initialisiert Detektoren aus Macro File erstellt mit legend-pygeom-l1000

/run/initialize

/RMG/GrabmayrGammaCascades/SetGammaCascadeRandomStartLocation 1
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 155 ./GrabmayrGammaCascades/156Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 64 157 ./GrabmayrGammaCascades/158Gd-5keV-cascades.txt
/RMG/GrabmayrGammaCascades/SetGammaCascadeFile 1 1 ./GrabmayrGammaCascades/2H-5keV-cascades.txt

/process/inactivate Scintillation      # Es sind nicht alle Szintillations Yields in Remage für L1000 definiert. Dadurch kann es zum Abbruch kommen.
#/process/optical/boundary/verbose 2

#/RMG/Output/IsotopeFilter/AddIsotope 77 32 # Ge77 filter
#/RMG/Output/IsotopeFilter/DiscardPhotonsIfIsotopeNotProduced true
/RMG/Output/NtuplePerDetector false

#/RMG/Generator/Confine Volume   ### Wähle alle relevanten Volumen von tank_water
#/RMG/Generator/Confinement/Physical/AddVolume water
#/RMG/Generator/Confinement/Physical/AddVolume skirt
#/RMG/Generator/Confinement/Physical/AddVolume foot
#/RMG/Generator/Confinement/Physical/AddVolume outercryostat
#/RMG/Generator/Select GPS
#/RMG/Generator/Confinement/MaxSamplingTrials 10000
#/gps/particle neutron
#/gps/energy 0.1 eV


/RMG/Generator/Select GPS
/RMG/Generator/Confine Volume
/RMG/Generator/Confinement/SamplingMode UnionAll
/RMG/Generator/Confinement/Geometrical/AddSolid Cylinder
/RMG/Generator/Confinement/Geometrical/CenterPositionX 0 mm
/RMG/Generator/Confinement/Geometrical/CenterPositionY 0 mm
/RMG/Generator/Confinement/Geometrical/CenterPositionZ -550 mm
/RMG/Generator/Confinement/Geometrical/Cylinder/InnerRadius 0 mm
/RMG/Generator/Confinement/Geometrical/Cylinder/OuterRadius 4300 mm
/RMG/Generator/Confinement/Geometrical/Cylinder/Height 8900 mm
/RMG/Generator/Confinement/Geometrical/Cylinder/StartingAngle 0 deg
/RMG/Generator/Confinement/Geometrical/Cylinder/SpanningAngle 360 deg
/RMG/Generator/Confinement/MaxSamplingTrials 10000
/gps/particle neutron
/gps/energy 0.1 eV
/gps/ang/type iso


#/RMG/Generator/Confine UnConfined
#/RMG/Generator/Select MUSUNCosmicMuons
#/RMG/Generator/MUSUNCosmicMuons/SetMUSUNFile musun/combined_file.dat

# 90min
/run/beamOn 1000000
